### ISSUE TITLE
Themes do not appear to work correctly when using Shiny as a package

### ISSUE THREAD

**Issue by kwathen** [BioPharmSoftGrp/BaSS#20] opened 2020-07-13 15:46 UTC
When creating a Shiny app as a package and using RunApp the red theme does not work.  The theme appears to be there but I think the reference is to the wrong place.

**Comment by jwildfire** [comment] 2020-09-14 12:48
Closing as duplicate of #65

**Closed by jwildfire** 2020-09-14 12:48 UTC
Labels: bug, duplicate
